# Generated by Django 3.0.6 on 2020-07-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_yektaneturl_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yektaneturl',
            name='shortcode',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
